name: Pack ubuntu template

on:
  push:
    branches:
      - main
    paths:
      - '**/*.pkr.hcl'
      - 'ubuntu-init/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  pack:
    runs-on: kubernetes
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      
    - name: Set env vars
      run: |
        echo "VAULT_ADDR=${{ vars.VAULT_ADDR }}" >> "$GITHUB_ENV"
        echo "WATCHER_ID=$RANDOM" >> "$GITHUB_ENV"

    - name: Vault secrets
      id: import-secrets
      uses: hashicorp/vault-action@v3
      with:
        url: ${{ vars.VAULT_ADDR }}
        method: kubernetes
        role: ghactions
        secrets: |
          secret/data/proxmox/api_token_id value | PM_API_TOKEN_ID ;
          secret/data/proxmox/api_token_secret value | PM_API_TOKEN_PASS

    - name: Get ISO hash
      run: |
        curl -o SHA256SUMS https://releases.ubuntu.com/jammy/SHA256SUMS

        # Extract the SHA256 checksum
        checksum=$(grep "live-server" SHA256SUMS  | awk '{print $1}')
        if [ -n "$checksum" ]; then
          echo "ISO_CHECKSUM=$checksum" >> $GITHUB_ENV
        else
          echo "ISO_CHECKSUM=none" >> $GITHUB_ENV
        fi

        echo "Got checksum: $(tail $GITHUB_ENV -n 1)"

#    - name: Start proxmox watcher
#      id: start-watcher
#      continue-on-error: true
#      shell: pwsh
#      run: |
#        /opt/powershell/pwsh -nologo -noprofile -file "./ci/start_watcher.ps1" "${{ vars.VM_WATCHER_HOST }}" "${{ vars.PACKER_VM_TEMPLATE_ID }}"
    
    - name: Proxmox ISO prep
      run: |
        # Set env vars for step only
        PM_API_TOKEN_ID="${{ steps.import-secrets.outputs.PM_API_TOKEN_ID }}"
        PM_API_TOKEN_PASS="${{ steps.import-secrets.outputs.PM_API_TOKEN_PASS }}"

        bash pm_iso_prep.sh

    - name: Pack
      id: pack-image
      run: |
        TEMPLATE="ubuntu.pkr.hcl"
        packer init ./templates/$TEMPLATE
        packer build -force -var "iso_hash=$ISO_CHECKSUM" ./templates/$TEMPLATE
    
    # Stop/destroy watcher
#    - name: Mutate watcher
#      if: steps.start-watcher.outcome == 'success'
#      shell: pwsh
#      run: |
#        /opt/powershell/pwsh -nologo -noprofile -file "./ci/mutate_watcher.ps1" "${{ vars.VM_WATCHER_HOST }}" ${{ steps.start-watcher.outputs.WATCHER_ACTIVE }} "${{ steps.pack-image.outcome }}"
        