name: Pack template

on:
  workflow_call:
    inputs:
      template:
        required: true
        type: string
      iso-hash:
        required: true
        type: string
      iso-filename:
        required: true
        type: string

jobs:
  pack:
    runs-on: kubernetes
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup `packer`
      uses: hashicorp/setup-packer@main

    - name: Vault secrets
      id: import-secrets
      uses: hashicorp/vault-action@v3
      with:
        url: ${{ vars.VAULT_ADDR }}
        method: kubernetes
        role: ghactions
        secrets: |
          secret/data/proxmox/api_token_id value | PKR_VAR_pm_api_token_id ;
          secret/data/proxmox/api_token_secret value | PKR_VAR_pm_api_token_secret ;
          secret/data/proxmox/ubuntu_template_vm_user value | PKR_VAR_template_user_password

    - name: debug
      run: |
        echo $(pwd)
        for i in $(find . -type d | grep -v ".git"); do
          echo $i
          ls $i
          echo "-----------"
        done

        echo "LS /"
        ls /

        [ -d /tmp ] && echo "/tmp exists" || echo "/tmp does NOT exist"

    - name: Pack
      id: pack-image
      run: |
        TARGET="${{ inputs.template }}"
        packer init ./templates/$TARGET
        packer build \
          -var "iso_hash=${{ inputs.iso-hash }}" \
          -var "iso_filename=${{ inputs.iso-filename }}" \
          -force \
          ./templates/$TARGET